### ISSUE TITLE
Scene graph generation

### ISSUE THREAD

**Issue by chibohe** [harrytea/Root#2]
Hi, great work！
Can you provide scene graph generation code or demo, thanks.

**Comment by harrytea** [comment]
Thank you for your interest! You can check out our demo on the project page https://harrytea.github.io/ROOT/. We'll release the weights later. Thanks again!

**Comment by chibohe** [comment]
> Thank you for your interest! You can check out our demo on the project page https://harrytea.github.io/ROOT/. We'll release the weights later. Thanks again!

Thank you for your replies. Could you please provide a simple requirements.txt.

**Comment by harrytea** [comment]
> > Thank you for your interest! You can check out our demo on the project page https://harrytea.github.io/ROOT/. We'll release the weights later. Thanks again!
> 
> Thank you for your replies. Could you please provide a simple requirements.txt.

accelerate==0.34.0
adjustText==1.2.0
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
async-timeout==4.0.3
attrs==24.2.0
av==13.0.0
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.1.0
contourpy==1.3.0
cycler==0.12.1
datasets==2.16.0
deepspeed==0.15.2
dill==0.3.7
diskcache==5.6.3
distro==1.9.0
docstring_parser==0.16
einops==0.8.0
exceptiongroup==1.2.2
fancycompleter==0.9.1
fastapi==0.115.2
filelock==3.15.4
flash-attn==2.6.3
fonttools==4.54.1
frozenlist==1.4.1
fsspec==2023.10.0
gguf==0.9.1
h11==0.14.0
hjson==3.1.0
httpcore==1.0.6
httptools==0.6.4
httpx==0.27.2
huggingface-hub==0.24.6
idna==3.8
importlib_metadata==8.5.0
interegular==0.3.3
Jinja2==3.1.4
jiter==0.6.1
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
lark==1.2.2
llvmlite==0.43.0
lm-format-enforcer==0.10.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
mistral_common==1.4.4
mpmath==1.3.0
msgpack==1.1.0
msgspec==0.18.6
multidict==6.1.0
multiprocess==0.70.15
nest-asyncio==1.6.0
networkx==3.3
ninja==1.11.1.1
numba==0.60.0
numpy==1.26.3
nvidia-cublas-cu11==11.11.3.6
nvidia-cuda-cupti-cu11==11.8.87
nvidia-cuda-nvrtc-cu11==11.8.89
nvidia-cuda-runtime-cu11==11.8.89
nvidia-cudnn-cu11==9.1.0.70
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.3.0.86
nvidia-cusolver-cu11==11.4.1.48
nvidia-cusparse-cu11==11.7.5.86
nvidia-ml-py==12.560.30
nvidia-nccl-cu11==2.20.5
nvidia-nvtx-cu11==11.8.86
openai==1.52.0
outlines==0.0.46
packaging==24.1
pandas==2.2.3
partial-json-parser==0.2.1.1.post4
pdbpp==0.10.3
peft==0.11.1
pillow==10.4.0
prometheus-fastapi-instrumentator==7.0.0
prometheus_client==0.21.0
propcache==0.2.0
protobuf==5.28.2
psutil==6.0.0
py-cpuinfo==9.0.0
pyairports==2.1.1
pyarrow==17.0.0
pyarrow-hotfix==0.6
pycountry==24.6.1
pydantic==2.9.2
pydantic_core==2.23.4
Pygments==2.18.0
pyparsing==3.2.0
pyrepl==0.9.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
qwen-vl-utils==0.0.8
ray==2.37.0
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rich==13.9.2
rpds-py==0.20.0
safetensors==0.4.5
scipy==1.14.1
sentencepiece==0.2.0
shtab==1.7.1
six==1.16.0
sniffio==1.3.1
socksio==1.0.0
starlette==0.40.0
sympy==1.13.2
tiktoken==0.7.0
tokenizers==0.20.1
tqdm==4.66.5
transformers==4.45.0
triton==3.0.0
trl==0.8.6
typing_extensions==4.12.2
tyro==0.8.12
tzdata==2024.2
urllib3==2.2.2
uvicorn==0.32.0
uvloop==0.21.0
watchfiles==0.24.0
websockets==13.1
wmctrl==0.5
xxhash==3.5.0
yarl==1.15.4
zipp==3.20.2


Maybe you can try this, and install pytorch==2.4.
If you have any other question, feel free to ask me, thanks.
pip install --no-cache-dir torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu118

**Comment by chibohe** [comment]
> > > Thank you for your interest! You can check out our demo on the project page https://harrytea.github.io/ROOT/. We'll release the weights later. Thanks again!
> > 
> > 
> > Thank you for your replies. Could you please provide a simple requirements.txt.
> 
> accelerate==0.34.0 adjustText==1.2.0 aiohappyeyeballs==2.4.3 aiohttp==3.10.10 aiosignal==1.3.1 annotated-types==0.7.0 anyio==4.6.2.post1 async-timeout==4.0.3 attrs==24.2.0 av==13.0.0 certifi==2024.8.30 charset-normalizer==3.3.2 click==8.1.7 cloudpickle==3.1.0 contourpy==1.3.0 cycler==0.12.1 datasets==2.16.0 deepspeed==0.15.2 dill==0.3.7 diskcache==5.6.3 distro==1.9.0 docstring_parser==0.16 einops==0.8.0 exceptiongroup==1.2.2 fancycompleter==0.9.1 fastapi==0.115.2 filelock==3.15.4 flash-attn==2.6.3 fonttools==4.54.1 frozenlist==1.4.1 fsspec==2023.10.0 gguf==0.9.1 h11==0.14.0 hjson==3.1.0 httpcore==1.0.6 httptools==0.6.4 httpx==0.27.2 huggingface-hub==0.24.6 idna==3.8 importlib_metadata==8.5.0 interegular==0.3.3 Jinja2==3.1.4 jiter==0.6.1 jsonschema==4.23.0 jsonschema-specifications==2024.10.1 kiwisolver==1.4.7 lark==1.2.2 llvmlite==0.43.0 lm-format-enforcer==0.10.6 markdown-it-py==3.0.0 MarkupSafe==2.1.5 matplotlib==3.9.2 mdurl==0.1.2 mistral_common==1.4.4 mpmath==1.3.0 msgpack==1.1.0 msgspec==0.18.6 multidict==6.1.0 multiprocess==0.70.15 nest-asyncio==1.6.0 networkx==3.3 ninja==1.11.1.1 numba==0.60.0 numpy==1.26.3 nvidia-cublas-cu11==11.11.3.6 nvidia-cuda-cupti-cu11==11.8.87 nvidia-cuda-nvrtc-cu11==11.8.89 nvidia-cuda-runtime-cu11==11.8.89 nvidia-cudnn-cu11==9.1.0.70 nvidia-cufft-cu11==10.9.0.58 nvidia-curand-cu11==10.3.0.86 nvidia-cusolver-cu11==11.4.1.48 nvidia-cusparse-cu11==11.7.5.86 nvidia-ml-py==12.560.30 nvidia-nccl-cu11==2.20.5 nvidia-nvtx-cu11==11.8.86 openai==1.52.0 outlines==0.0.46 packaging==24.1 pandas==2.2.3 partial-json-parser==0.2.1.1.post4 pdbpp==0.10.3 peft==0.11.1 pillow==10.4.0 prometheus-fastapi-instrumentator==7.0.0 prometheus_client==0.21.0 propcache==0.2.0 protobuf==5.28.2 psutil==6.0.0 py-cpuinfo==9.0.0 pyairports==2.1.1 pyarrow==17.0.0 pyarrow-hotfix==0.6 pycountry==24.6.1 pydantic==2.9.2 pydantic_core==2.23.4 Pygments==2.18.0 pyparsing==3.2.0 pyrepl==0.9.0 python-dateutil==2.9.0.post0 python-dotenv==1.0.1 pytz==2024.2 PyYAML==6.0.2 pyzmq==26.2.0 qwen-vl-utils==0.0.8 ray==2.37.0 referencing==0.35.1 regex==2024.7.24 requests==2.32.3 rich==13.9.2 rpds-py==0.20.0 safetensors==0.4.5 scipy==1.14.1 sentencepiece==0.2.0 shtab==1.7.1 six==1.16.0 sniffio==1.3.1 socksio==1.0.0 starlette==0.40.0 sympy==1.13.2 tiktoken==0.7.0 tokenizers==0.20.1 tqdm==4.66.5 transformers==4.45.0 triton==3.0.0 trl==0.8.6 typing_extensions==4.12.2 tyro==0.8.12 tzdata==2024.2 urllib3==2.2.2 uvicorn==0.32.0 uvloop==0.21.0 watchfiles==0.24.0 websockets==13.1 wmctrl==0.5 xxhash==3.5.0 yarl==1.15.4 zipp==3.20.2
> 
> Maybe you can try this, and install pytorch==2.4. If you have any other question, feel free to ask me, thanks. pip install --no-cache-dir torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu118

Got it. Thank you so much!
