### ISSUE TITLE
code can not be used

### ISSUE THREAD

**Issue by 77h2l** [harrytea/Root#3]
seems that unable to use the code, as some model weights are not clearly mentioned, and gpt4v api is not available to call

**Comment by harrytea** [comment]
The code can run on my server, please explain the reason for the error?

**Comment by harrytea** [comment]
You can download our fine tuned model [here](https://huggingface.co/harrytea/ROOT). GPT-4V is a commercial model that requires payment to use, and you need to provide your API code.

**Comment by 77h2l** [comment]
ok, here is what i have found:
1.[gpt4-v](https://github.com/harrytea/ROOT/blob/main/foundation/indoor_object.py#L26) there is a bug,which should be gpt4_azure
2.the "ckpts" dir is empty, which means we need to download the related models first?
3.as for the vlm handler, can we use the open-sourced vlm models?

**Comment by harrytea** [comment]
Thank you, I have fixed the bugs. If you want to try other models in the object perception, the results may be worse than GPT-4V. We still recommend using GPT-4V in the first step.

**Comment by 77h2l** [comment]
another issue:

Local weights not found at ckpts/depth_anything_vitl14.pth, downloading from https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth
Downloading: "https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth" to /root/.cache/torch/hub/checkpoints/depth_anything_vitl14.pth


however, the url seems to be invalid

**Comment by harrytea** [comment]
The URL is working on my end, you may need help with a VPN.

(python) ➜ ~ wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth
--2024-12-17 11:35:06--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth
Resolving huggingface.co (huggingface.co)... 69.171.224.40, 2a03:2880:f134:83:face:b00c:0:25de
Connecting to huggingface.co (huggingface.co)|69.171.224.40|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs-us-1.hf.co/repos/b2/a8/b2a84b9a6ef705fba73e7ccec6a9728b3427d8b4c7f536eae186110f0cbd700f/6c6a383e33e51c5fdfbf31e7ebcda943973a9e6a1cbef1564afe58d7f2e8fe63?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27depth_anything_vitl14.pth%3B+filename%3D%22depth_anything_vitl14.pth%22%3B&Expires=1734665711&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczNDY2NTcxMX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2IyL2E4L2IyYTg0YjlhNmVmNzA1ZmJhNzNlN2NjZWM2YTk3MjhiMzQyN2Q4YjRjN2Y1MzZlYWUxODYxMTBmMGNiZDcwMGYvNmM2YTM4M2UzM2U1MWM1ZmRmYmYzMWU3ZWJjZGE5NDM5NzNhOWU2YTFjYmVmMTU2NGFmZTU4ZDdmMmU4ZmU2Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=OckbxzO5ZoSRwbHxHa2ld6e4omeVnHM5ivzU4T1GOJJl1NvTqj9HUujU%7EYBVhbvsKSmYNzpYiqfYxDJJ4Gsi0WF0lBzS6cGsCx5ew05grGcWqlUO749CslxYxKrsRxp3m1v9gco9eka9ZzhZEABXVDXpE0%7EddM5qXVHxmN2Ad8f5oJ4nXGz1r3PrcEK6j%7EySq2ASPpQWa6FK-zsLsfiSTZ%7E8DnirMJWTEPooiI84pZrtYaTYPcPgQZZc0VBFrR7a2VgyuGDhq3zE3oiU4evHkb9J2r9vJALYmCGCLqV7BdscUTq7TUG5hkb3YFsW%7Ef-p2Oe195%7EeZy%7EgGskSKDXNDA__&Key-Pair-Id=K24J24Z295AEI9 [following]
--2024-12-17 11:35:12--  https://cdn-lfs-us-1.hf.co/repos/b2/a8/b2a84b9a6ef705fba73e7ccec6a9728b3427d8b4c7f536eae186110f0cbd700f/6c6a383e33e51c5fdfbf31e7ebcda943973a9e6a1cbef1564afe58d7f2e8fe63?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27depth_anything_vitl14.pth%3B+filename%3D%22depth_anything_vitl14.pth%22%3B&Expires=1734665711&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczNDY2NTcxMX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2IyL2E4L2IyYTg0YjlhNmVmNzA1ZmJhNzNlN2NjZWM2YTk3MjhiMzQyN2Q4YjRjN2Y1MzZlYWUxODYxMTBmMGNiZDcwMGYvNmM2YTM4M2UzM2U1MWM1ZmRmYmYzMWU3ZWJjZGE5NDM5NzNhOWU2YTFjYmVmMTU2NGFmZTU4ZDdmMmU4ZmU2Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=OckbxzO5ZoSRwbHxHa2ld6e4omeVnHM5ivzU4T1GOJJl1NvTqj9HUujU%7EYBVhbvsKSmYNzpYiqfYxDJJ4Gsi0WF0lBzS6cGsCx5ew05grGcWqlUO749CslxYxKrsRxp3m1v9gco9eka9ZzhZEABXVDXpE0%7EddM5qXVHxmN2Ad8f5oJ4nXGz1r3PrcEK6j%7EySq2ASPpQWa6FK-zsLsfiSTZ%7E8DnirMJWTEPooiI84pZrtYaTYPcPgQZZc0VBFrR7a2VgyuGDhq3zE3oiU4evHkb9J2r9vJALYmCGCLqV7BdscUTq7TUG5hkb3YFsW%7Ef-p2Oe195%7EeZy%7EgGskSKDXNDA__&Key-Pair-Id=K24J24Z295AEI9
Resolving cdn-lfs-us-1.hf.co (cdn-lfs-us-1.hf.co)... 18.66.147.34, 18.66.147.55, 18.66.147.29, ...
Connecting to cdn-lfs-us-1.hf.co (cdn-lfs-us-1.hf.co)|18.66.147.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1341401882 (1.2G) [binary/octet-stream]
Saving to: ‘depth_anything_vitl14.pth’

depth_anything_vitl14.pth                              6%[======>                                                                                                               ]  80.05M  22.8MB/s    eta 81s

**Comment by 77h2l** [comment]
@harrytea I have successfully run the code, and I replace the vlm model to several different types, including close-source gpt4o, and other open-sources vlm relations, however the effect is rather poor even on the given example pics.
Since I want to use this on the specific domain which the scene is more complex than the standard demo pics, how can we finetune the vlm model to generate a better scene graph, can you provide a detailed tutorial or the key data formats so that able to sft the vlm,thx

**Comment by harrytea** [comment]
Can you obtain the results of the demo? We conducted tests on several datasets in the paper, all of which are ready-made open-source datasets. Perhaps there is a significant gap between your scenes and the data in the paper, otherwise poor results would not have occurred.
The model is divided into many steps, I guess there is a problem with your intermediate steps. Perhaps you can show the results of each step to see where the problem lies, or perhaps you can refer to our demo demonstration to correct the errors in each step.

Due to the complexity of the project and company policies restricting direct open-source contributions. The current repository's code has been rewritten by me (Slightly different from the original code within the company, but still able to achieve similar performance after testing). 

For sft, we will soon organize and release the script. Thanks.
